<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kas_keluar extends CI_Controller
{
    var $judul_page = 'Kas Keluar';
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kas_keluar_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $kas_keluar = $this->Kas_keluar_model->get_all();

        $data = array(
            'kas_keluar_data' => $kas_keluar,
            'judul_page' => $this->judul_page,
            'konten' => 'kas_keluar/kas_keluar_list',
        );
        $this->load->view('v_index', $data);
    }

    

    public function create() 
    {
        $data = array(
            'judul_page' => $this->judul_page,
            'konten' => 'kas_keluar/kas_keluar_form',
            'judul_form' => 'Tambah '.$this->judul_page,
            'button' => 'Simpan',
            'action' => site_url('kas_keluar/create_action'),
	    'id_kas_keluar' => set_value('id_kas_keluar'),
	    'keterangan' => set_value('keterangan'),
	    'jumlah' => set_value('jumlah'),
	    'tanggal' => set_value('tanggal'),
	);
        $this->load->view('v_index', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'keterangan' => $this->input->post('keterangan',TRUE),
		'jumlah' => $this->input->post('jumlah',TRUE),
		'tanggal' => $this->input->post('tanggal',TRUE),
        'created_at' => get_waktu(),
        'user_by' => $this->session->userdata('id_user')
	    );

            $this->Kas_keluar_model->insert($data);
            $this->session->set_flashdata('message', message('success','Data berhasil disimpan'));
            redirect(site_url('kas_keluar'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Kas_keluar_model->get_by_id($id);

        if ($row) {
            $data = array(
                'judul_page' => $this->judul_page,
                'konten' => 'kas_keluar/kas_keluar_form',
                'judul_form' => 'Ubah '.$this->judul_page,
                'button' => 'Update',
                'action' => site_url('kas_keluar/update_action'),
		'id_kas_keluar' => set_value('id_kas_keluar', $row->id_kas_keluar),
		'keterangan' => set_value('keterangan', $row->keterangan),
		'jumlah' => set_value('jumlah', $row->jumlah),
		'tanggal' => set_value('tanggal', $row->tanggal),
	    );
            $this->load->view('v_index', $data);
        } else {
            $this->session->set_flashdata('message', message('danger','Data tidak ditemukan'));
            redirect(site_url('kas_keluar'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_kas_keluar', TRUE));
        } else {
            $data = array(
		'keterangan' => $this->input->post('keterangan',TRUE),
		'jumlah' => $this->input->post('jumlah',TRUE),
		'tanggal' => $this->input->post('tanggal',TRUE),
	    );

            $this->Kas_keluar_model->update($this->input->post('id_kas_keluar', TRUE), $data);
            $this->session->set_flashdata('message', message('success','Data berhasil diupdate'));
            redirect(site_url('kas_keluar'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Kas_keluar_model->get_by_id($id);

        if ($row) {
            $this->Kas_keluar_model->delete($id);
            $this->session->set_flashdata('message', message('success','Data berhasil dihapus'));
            redirect(site_url('kas_keluar'));
        } else {
            $this->session->set_flashdata('message', message('danger','Data tidak ditemukan'));
            redirect(site_url('kas_keluar'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('keterangan', 'keterangan', 'trim|required');
	$this->form_validation->set_rules('jumlah', 'jumlah', 'trim|required');
	$this->form_validation->set_rules('tanggal', 'tanggal', 'trim|required');

	$this->form_validation->set_rules('id_kas_keluar', 'id_kas_keluar', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Kas_keluar.php */
/* Location: ./application/controllers/Kas_keluar.php */
/* Please DO NOT modify this information : */
/* Generated by Boy Kurniawan 2022-02-12 08:12:49 */
/* https://jualkoding.com */