<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Point_bonus extends CI_Controller
{
    var $judul_page = 'Setting Bonus Point';
    function __construct()
    {
        parent::__construct();
        $this->load->model('Point_bonus_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $point_bonus = $this->Point_bonus_model->get_all();

        $data = array(
            'point_bonus_data' => $point_bonus,
            'judul_page' => $this->judul_page,
            'konten' => 'point_bonus/point_bonus_list',
        );
        $this->load->view('v_index', $data);
    }

    

    public function create() 
    {
        $data = array(
            'judul_page' => $this->judul_page,
            'konten' => 'point_bonus/point_bonus_form',
            'judul_form' => 'Tambah '.$this->judul_page,
            'button' => 'Simpan',
            'action' => site_url('point_bonus/create_action'),
	    'id_set_point' => set_value('id_set_point'),
	    'kode_point' => set_value('kode_point'),
	    'point' => set_value('point'),
	    'keterangan' => set_value('keterangan'),
	);
        $this->load->view('v_index', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'kode_point' => $this->input->post('kode_point',TRUE),
		'point' => $this->input->post('point',TRUE),
		'keterangan' => $this->input->post('keterangan',TRUE),
	    );

            $this->Point_bonus_model->insert($data);
            $this->session->set_flashdata('message', message('success','Data berhasil disimpan'));
            redirect(site_url('point_bonus'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Point_bonus_model->get_by_id($id);

        if ($row) {
            $data = array(
                'judul_page' => $this->judul_page,
                'konten' => 'point_bonus/point_bonus_form',
                'judul_form' => 'Ubah '.$this->judul_page,
                'button' => 'Update',
                'action' => site_url('point_bonus/update_action'),
		'id_set_point' => set_value('id_set_point', $row->id_set_point),
		'kode_point' => set_value('kode_point', $row->kode_point),
		'point' => set_value('point', $row->point),
		'keterangan' => set_value('keterangan', $row->keterangan),
	    );
            $this->load->view('v_index', $data);
        } else {
            $this->session->set_flashdata('message', message('danger','Data tidak ditemukan'));
            redirect(site_url('point_bonus'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_set_point', TRUE));
        } else {
            $data = array(
		'kode_point' => $this->input->post('kode_point',TRUE),
		'point' => $this->input->post('point',TRUE),
		'keterangan' => $this->input->post('keterangan',TRUE),
	    );

            $this->Point_bonus_model->update($this->input->post('id_set_point', TRUE), $data);
            $this->session->set_flashdata('message', message('success','Data berhasil diupdate'));
            redirect(site_url('point_bonus'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Point_bonus_model->get_by_id($id);

        if ($row) {
            $this->Point_bonus_model->delete($id);
            $this->session->set_flashdata('message', message('success','Data berhasil dihapus'));
            redirect(site_url('point_bonus'));
        } else {
            $this->session->set_flashdata('message', message('danger','Data tidak ditemukan'));
            redirect(site_url('point_bonus'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('kode_point', 'kode point', 'trim|required');
	$this->form_validation->set_rules('point', 'point', 'trim|required');
	$this->form_validation->set_rules('keterangan', 'keterangan', 'trim|required');

	$this->form_validation->set_rules('id_set_point', 'id_set_point', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Point_bonus.php */
/* Location: ./application/controllers/Point_bonus.php */
/* Please DO NOT modify this information : */
/* Generated by Boy Kurniawan 2022-02-12 08:12:44 */
/* https://jualkoding.com */