<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Subscribe extends CI_Controller
{
    var $judul_page = 'subscribe_list';
    function __construct()
    {
        parent::__construct();
        $this->load->model('Subscribe_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $subscribe = $this->Subscribe_model->get_all();

        $data = array(
            'subscribe_data' => $subscribe,
            'judul_page' => $this->judul_page,
            'konten' => 'subscribe/subscribe_list',
        );
        $this->load->view('v_index', $data);
    }

    

    public function create() 
    {
        $data = array(
            'judul_page' => $this->judul_page,
            'konten' => 'subscribe/subscribe_form',
            'judul_form' => 'Tambah '.$this->judul_page,
            'button' => 'Simpan',
            'action' => site_url('subscribe/create_action'),
	    'id_subscribe' => set_value('id_subscribe'),
	    'email' => set_value('email'),
	    'created_at' => set_value('created_at'),
	);
        $this->load->view('v_index', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'email' => $this->input->post('email',TRUE),
		'created_at' => $this->input->post('created_at',TRUE),
	    );

            $this->Subscribe_model->insert($data);
            $this->session->set_flashdata('message', message('success','Data berhasil disimpan'));
            redirect(site_url('subscribe'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Subscribe_model->get_by_id($id);

        if ($row) {
            $data = array(
                'judul_page' => $this->judul_page,
                'konten' => 'subscribe/subscribe_form',
                'judul_form' => 'Ubah '.$this->judul_page,
                'button' => 'Update',
                'action' => site_url('subscribe/update_action'),
		'id_subscribe' => set_value('id_subscribe', $row->id_subscribe),
		'email' => set_value('email', $row->email),
		'created_at' => set_value('created_at', $row->created_at),
	    );
            $this->load->view('v_index', $data);
        } else {
            $this->session->set_flashdata('message', message('danger','Data tidak ditemukan'));
            redirect(site_url('subscribe'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_subscribe', TRUE));
        } else {
            $data = array(
		'email' => $this->input->post('email',TRUE),
		'created_at' => $this->input->post('created_at',TRUE),
	    );

            $this->Subscribe_model->update($this->input->post('id_subscribe', TRUE), $data);
            $this->session->set_flashdata('message', message('success','Data berhasil diupdate'));
            redirect(site_url('subscribe'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Subscribe_model->get_by_id($id);

        if ($row) {
            $this->Subscribe_model->delete($id);
            $this->session->set_flashdata('message', message('success','Data berhasil dihapus'));
            redirect(site_url('subscribe'));
        } else {
            $this->session->set_flashdata('message', message('danger','Data tidak ditemukan'));
            redirect(site_url('subscribe'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('email', 'email', 'trim|required');
	$this->form_validation->set_rules('created_at', 'created at', 'trim|required');

	$this->form_validation->set_rules('id_subscribe', 'id_subscribe', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Subscribe.php */
/* Location: ./application/controllers/Subscribe.php */
/* Please DO NOT modify this information : */
/* Generated by Boy Kurniawan 2022-05-21 06:18:47 */
/* https://jualkoding.com */