<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Testimoni extends CI_Controller
{
    var $judul_page = 'testimoni_list';
    function __construct()
    {
        parent::__construct();
        $this->load->model('Testimoni_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $testimoni = $this->Testimoni_model->get_all();

        $data = array(
            'testimoni_data' => $testimoni,
            'judul_page' => $this->judul_page,
            'konten' => 'testimoni/testimoni_list',
        );
        $this->load->view('v_index', $data);
    }

    

    public function create() 
    {
        $data = array(
            'judul_page' => $this->judul_page,
            'konten' => 'testimoni/testimoni_form',
            'judul_form' => 'Tambah '.$this->judul_page,
            'button' => 'Simpan',
            'action' => site_url('testimoni/create_action'),
	    'id_testimoni' => set_value('id_testimoni'),
	    'foto' => set_value('foto'),
	    'link' => set_value('link'),
	);
        $this->load->view('v_index', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {

            $img = upload_gambar_biasa('produk', 'image/testimoni/', 'jpg|png|jpeg', 10000, 'foto');

            $data = array(
		'foto' => $img,
		'link' => $this->input->post('link',TRUE),
	    );

            $this->Testimoni_model->insert($data);
            $this->session->set_flashdata('message', message('success','Data berhasil disimpan'));
            redirect(site_url('testimoni'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Testimoni_model->get_by_id($id);

        if ($row) {
            $data = array(
                'judul_page' => $this->judul_page,
                'konten' => 'testimoni/testimoni_form',
                'judul_form' => 'Ubah '.$this->judul_page,
                'button' => 'Update',
                'action' => site_url('testimoni/update_action'),
		'id_testimoni' => set_value('id_testimoni', $row->id_testimoni),
		'foto' => set_value('foto', $row->foto),
		'link' => set_value('link', $row->link),
	    );
            $this->load->view('v_index', $data);
        } else {
            $this->session->set_flashdata('message', message('danger','Data tidak ditemukan'));
            redirect(site_url('testimoni'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_testimoni', TRUE));
        } else {
            $data = array(
		'foto' => $retVal = ($_FILES['foto']['name'] == '') ? $_POST['foto_old'] : upload_gambar_biasa('produk', 'image/produk/', 'jpeg|png|jpg|gif', 10000, 'foto'),
		'link' => $this->input->post('link',TRUE),
	    );

            $this->Testimoni_model->update($this->input->post('id_testimoni', TRUE), $data);
            $this->session->set_flashdata('message', message('success','Data berhasil diupdate'));
            redirect(site_url('testimoni'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Testimoni_model->get_by_id($id);

        if ($row) {
            $this->Testimoni_model->delete($id);
            $this->session->set_flashdata('message', message('success','Data berhasil dihapus'));
            redirect(site_url('testimoni'));
        } else {
            $this->session->set_flashdata('message', message('danger','Data tidak ditemukan'));
            redirect(site_url('testimoni'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('link', 'link', 'trim|required');

	$this->form_validation->set_rules('id_testimoni', 'id_testimoni', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Testimoni.php */
/* Location: ./application/controllers/Testimoni.php */
/* Please DO NOT modify this information : */
/* Generated by Boy Kurniawan 2022-05-20 06:01:36 */
/* https://jualkoding.com */