<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Member_model extends CI_Model
{

    public $table = 'member';
    public $id = 'id_member';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_member', $q);
	$this->db->or_like('kode_member', $q);
	$this->db->or_like('nama_lengkap', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->or_like('instagram', $q);
	$this->db->or_like('facebook', $q);
	$this->db->or_like('shopee', $q);
	$this->db->or_like('tokopedia', $q);
	$this->db->or_like('bukalapak', $q);
	$this->db->or_like('lazada', $q);
	$this->db->or_like('jenis_identitas', $q);
	$this->db->or_like('no_identitas', $q);
	$this->db->or_like('nama_bank', $q);
	$this->db->or_like('no_rekening', $q);
	$this->db->or_like('atas_nama', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('id_kabupaten', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('level', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_member', $q);
	$this->db->or_like('kode_member', $q);
	$this->db->or_like('nama_lengkap', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->or_like('instagram', $q);
	$this->db->or_like('facebook', $q);
	$this->db->or_like('shopee', $q);
	$this->db->or_like('tokopedia', $q);
	$this->db->or_like('bukalapak', $q);
	$this->db->or_like('lazada', $q);
	$this->db->or_like('jenis_identitas', $q);
	$this->db->or_like('no_identitas', $q);
	$this->db->or_like('nama_bank', $q);
	$this->db->or_like('no_rekening', $q);
	$this->db->or_like('atas_nama', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('id_kabupaten', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('level', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Member_model.php */
/* Location: ./application/models/Member_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-02-04 08:39:21 */
/* http://harviacode.com */